#!/bin/bash
#
# sync-from-live.sh — Pull live site into local DDEV
# Part of wp-ddev-tools: https://github.com/yourname/wp-ddev-tools
#
# Usage: ./sync-from-live.sh [--skip-uploads]
#
# Reads connection details from .wp-ddev-tools.conf (generated by wp-ddev-setup.sh)
# or falls back to environment variables / manual config below.
#

# ─── Load Config ───
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FILE="$SCRIPT_DIR/.wp-ddev-tools.conf"

if [ -f "$CONF_FILE" ]; then
    source "$CONF_FILE"
else
    # ─── Manual Configuration (edit these if not using .wp-ddev-tools.conf) ───
    SSH_HOST="your-ssh-alias"
    SSH_PORT="22"
    REMOTE_ROOT="~/public_html"
    LOCAL_URL="https://your-project.ddev.site"
    LIVE_URL="https://your-live-site.com"
fi

BACKUP_FILE="wp-ddev-sync-backup.sql"

# ─── Colors ───
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
DIM='\033[0;90m'
BOLD='\033[1m'
NC='\033[0m'

# ─── Flags ───
SKIP_UPLOADS=false
for arg in "$@"; do
    case $arg in
        --skip-uploads) SKIP_UPLOADS=true ;;
        --help|-h)
            echo "Usage: ./sync-from-live.sh [--skip-uploads]"
            echo ""
            echo "Pulls live site database and files into local DDEV."
            echo "Creates a snapshot before changes for easy rollback."
            echo ""
            echo "Options:"
            echo "  --skip-uploads  Skip syncing wp-content/uploads (faster)"
            echo "  --help, -h      Show this help"
            echo ""
            echo "Config: .wp-ddev-tools.conf (or edit this script directly)"
            exit 0
            ;;
    esac
done

# ─── Helpers ───
STEP=0
step() {
    STEP=$((STEP + 1))
    echo ""
    echo -e "${BOLD}${CYAN}[$STEP/$TOTAL] $1${NC}"
}

ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
warn() { echo -e "  ${YELLOW}~${NC} $1"; }
fail() { echo -e "  ${RED}✗ $1${NC}"; exit 1; }

# ─── Determine total steps ───
if [ "$SKIP_UPLOADS" = true ]; then
    TOTAL=7
else
    TOTAL=8
fi

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  Sync Live → Local${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

# ─── Step 1: SSH Agent ───
step "Loading SSH key..."

if [ -z "$SSH_AUTH_SOCK" ]; then
    eval "$(ssh-agent -s)" > /dev/null 2>&1
fi

# Add key if not already loaded
ssh-add -l > /dev/null 2>&1 || ssh-add 2>/dev/null || fail "Could not load SSH key"
ok "SSH key loaded"

ssh -o ConnectTimeout=5 "$SSH_HOST" "echo connected" > /dev/null 2>&1 || fail "Cannot connect to $SSH_HOST"
ok "SSH connection verified"

# ─── Step 2: Verify DDEV ───
step "Checking DDEV..."

ddev describe > /dev/null 2>&1
if [ $? -ne 0 ]; then
    warn "DDEV not running, starting..."
    ddev start || fail "Could not start DDEV"
fi
ok "DDEV is running"

# ─── Step 3: Snapshot ───
step "Snapshotting local database..."

SNAPSHOT_NAME="pre-sync-$(date +%Y%m%d-%H%M%S)"
ddev snapshot --name="$SNAPSHOT_NAME" > /dev/null 2>&1 || fail "Could not create snapshot"
ok "Snapshot: $SNAPSHOT_NAME"

# ─── Step 4: Uploads ───
if [ "$SKIP_UPLOADS" = false ]; then
    step "Syncing uploads from live..."
    rsync -avz --stats -e "ssh -p $SSH_PORT" \
        "$SSH_HOST:$REMOTE_ROOT/wp-content/uploads/" \
        wp-content/uploads/ 2>&1 | tail -3
    ok "Uploads synced"
fi

# ─── Step 5: Export live DB ───
step "Exporting live database..."

ssh "$SSH_HOST" "cd $REMOTE_ROOT && wp db export ~/$BACKUP_FILE" > /dev/null 2>&1 || fail "Could not export live database"
ok "Live database exported"

# ─── Step 6: Download and import ───
step "Downloading and importing database..."

scp "$SSH_HOST:~/$BACKUP_FILE" . > /dev/null 2>&1 || fail "Could not download database"
ok "Downloaded ($(du -h $BACKUP_FILE | cut -f1))"

ddev import-db --file="$BACKUP_FILE" > /dev/null 2>&1 || fail "Could not import database"
ok "Database imported"

rm -f "$BACKUP_FILE"
ssh "$SSH_HOST" "rm -f ~/$BACKUP_FILE" > /dev/null 2>&1
ok "Temp files cleaned up"

# ─── Step 7: Restart DDEV ───
step "Restarting DDEV (applying config hooks)..."

ddev restart > /dev/null 2>&1 || fail "Could not restart DDEV"
ok "DDEV restarted"

# ─── Step 8: Fix URLs ───
step "Replacing live URLs with local..."

REPLACEMENTS=$(ddev wp search-replace "$LIVE_URL" "$LOCAL_URL" --all-tables 2>&1 | grep -o '[0-9]* replacements' | head -1)
ok "search-replace: $REPLACEMENTS"

ddev wp option update siteurl "$LOCAL_URL" > /dev/null 2>&1
ddev wp option update home "$LOCAL_URL" > /dev/null 2>&1
ddev wp cache flush > /dev/null 2>&1
ddev wp rewrite flush > /dev/null 2>&1
ok "URLs updated and caches flushed"

# ─── Summary ───
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  ${GREEN}✓ Sync complete!${NC}"
echo -e "  ${DIM}Local site: $LOCAL_URL${NC}"
echo -e "  ${DIM}Snapshot:   $SNAPSHOT_NAME${NC}"
echo -e "  ${DIM}To undo:    ddev snapshot restore $SNAPSHOT_NAME${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
