#!/bin/bash
#
# verify-env.sh — Compare local DDEV environment vs live site
# Part of wp-ddev-tools: https://github.com/yourname/wp-ddev-tools
#
# Usage: ./verify-env.sh
#
# Reads connection details from .wp-ddev-tools.conf (generated by wp-ddev-setup.sh)
# or falls back to manual config below.
#

# ─── Load Config ───
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FILE="$SCRIPT_DIR/.wp-ddev-tools.conf"

if [ -f "$CONF_FILE" ]; then
    source "$CONF_FILE"
else
    # ─── Manual Configuration ───
    SSH_HOST="your-ssh-alias"
    REMOTE_ROOT="~/public_html"
fi

# ─── Colors ───
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
DIM='\033[0;90m'
BOLD='\033[1m'
NC='\033[0m'

pass=0
warn_count=0
fail_count=0

compare() {
    local label="$1" local_val="$2" live_val="$3"
    if [ "$local_val" = "$live_val" ]; then
        echo -e "  ${GREEN}✓${NC} ${label}: ${local_val}"
        pass=$((pass + 1))
    else
        echo -e "  ${RED}✗${NC} ${label}"
        echo -e "    ${DIM}Local:${NC} ${local_val}"
        echo -e "    ${DIM}Live: ${NC} ${live_val}"
        fail_count=$((fail_count + 1))
    fi
}

compare_loose() {
    local label="$1" local_val="$2" live_val="$3"
    if [ "$local_val" = "$live_val" ]; then
        echo -e "  ${GREEN}✓${NC} ${label}: ${local_val}"
        pass=$((pass + 1))
    else
        echo -e "  ${YELLOW}~${NC} ${label}"
        echo -e "    ${DIM}Local:${NC} ${local_val}"
        echo -e "    ${DIM}Live: ${NC} ${live_val}"
        warn_count=$((warn_count + 1))
    fi
}

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  Environment Parity Check: Local vs Live${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ─── Gather local data ───
echo -e "${CYAN}Gathering local environment info...${NC}"
LOCAL_WP_VER=$(ddev wp core version 2>/dev/null || echo "unknown")
LOCAL_PHP_VER=$(ddev php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;" 2>/dev/null || echo "unknown")
LOCAL_DB_VER=$(ddev mysql -e "SELECT VERSION();" -sN 2>/dev/null | head -1 || echo "unknown")
LOCAL_THEME=$(ddev wp option get template 2>/dev/null || echo "unknown")
LOCAL_PREFIX=$(ddev wp config get table_prefix 2>/dev/null || echo "unknown")
LOCAL_SITEURL=$(ddev wp option get siteurl 2>/dev/null || echo "unknown")
LOCAL_HOME=$(ddev wp option get home 2>/dev/null || echo "unknown")
LOCAL_BLOGNAME=$(ddev wp option get blogname 2>/dev/null || echo "unknown")
LOCAL_PLUGINS=$(ddev wp plugin list --status=active --format=csv --fields=name,version 2>/dev/null | tail -n +2 | sort || echo "")
LOCAL_PLUGIN_COUNT=$(echo "$LOCAL_PLUGINS" | grep -c ',' || echo "0")

# ─── Gather ALL live data in ONE SSH call ───
echo -e "${CYAN}Gathering live environment info via SSH (single connection)...${NC}"

REMOTE_SCRIPT=$(mktemp)
cat > "$REMOTE_SCRIPT" << ENDSCRIPT
cd $REMOTE_ROOT
echo "===WP_VER==="
wp core version 2>/dev/null || echo "unknown"
echo "===PHP_VER==="
php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION.PHP_EOL;' 2>/dev/null || echo "unknown"
echo "===DB_VER==="
wp db query 'SELECT VERSION();' --skip-column-names 2>/dev/null | head -1 || echo "unknown"
echo "===THEME==="
wp option get template 2>/dev/null || echo "unknown"
echo "===PREFIX==="
wp config get table_prefix 2>/dev/null || echo "unknown"
echo "===SITEURL==="
wp option get siteurl 2>/dev/null || echo "unknown"
echo "===HOME==="
wp option get home 2>/dev/null || echo "unknown"
echo "===BLOGNAME==="
wp option get blogname 2>/dev/null || echo "unknown"
echo "===PLUGINS==="
wp plugin list --status=active --format=csv --fields=name,version 2>/dev/null | tail -n +2 | sort || echo ""
echo "===END==="
ENDSCRIPT

LIVE_DATA=$(ssh "$SSH_HOST" 'bash -s' < "$REMOTE_SCRIPT" 2>/dev/null)
SSH_EXIT=$?
rm -f "$REMOTE_SCRIPT"

if [ $SSH_EXIT -ne 0 ] || [ -z "$LIVE_DATA" ]; then
    echo ""
    echo -e "  ${RED}✗ SSH connection failed!${NC}"
    echo -e "  ${DIM}Try: ssh $SSH_HOST \"echo connected\"${NC}"
    echo -e "  ${DIM}Or load your key: eval \"\$(ssh-agent -s)\" && ssh-add${NC}"
    echo ""
    exit 1
fi

echo -e "${GREEN}SSH connection successful.${NC}"

# ─── Parse live data ───
extract_section() {
    echo "$LIVE_DATA" | sed -n "/===$1===/,/===/p" | grep -v "===" | head -1
}

extract_multiline() {
    echo "$LIVE_DATA" | sed -n "/===$1===/,/===/p" | grep -v "==="
}

LIVE_WP_VER=$(extract_section "WP_VER")
LIVE_PHP_VER=$(extract_section "PHP_VER")
LIVE_DB_VER=$(extract_section "DB_VER")
LIVE_THEME=$(extract_section "THEME")
LIVE_PREFIX=$(extract_section "PREFIX")
LIVE_SITEURL=$(extract_section "SITEURL")
LIVE_HOME=$(extract_section "HOME")
LIVE_BLOGNAME=$(extract_section "BLOGNAME")
LIVE_PLUGINS=$(extract_multiline "PLUGINS")
LIVE_PLUGIN_COUNT=$(echo "$LIVE_PLUGINS" | grep -c ',' || echo "0")

echo ""

# ─── Core Versions ───
echo -e "${BOLD}Core Versions${NC}"
compare "WordPress" "$LOCAL_WP_VER" "$LIVE_WP_VER"
compare "PHP" "$LOCAL_PHP_VER" "$LIVE_PHP_VER"
compare_loose "Database" "$LOCAL_DB_VER" "$LIVE_DB_VER"
echo ""

# ─── Configuration ───
echo -e "${BOLD}Configuration${NC}"
compare "Table prefix" "$LOCAL_PREFIX" "$LIVE_PREFIX"
compare "Active theme" "$LOCAL_THEME" "$LIVE_THEME"
compare "Blog name" "$LOCAL_BLOGNAME" "$LIVE_BLOGNAME"
echo ""

# ─── URLs ───
echo -e "${BOLD}URLs ${DIM}(these SHOULD differ between local and live)${NC}"
echo -e "  ${DIM}Local siteurl:${NC} $LOCAL_SITEURL"
echo -e "  ${DIM}Live siteurl: ${NC} $LIVE_SITEURL"
echo -e "  ${DIM}Local home:   ${NC} $LOCAL_HOME"
echo -e "  ${DIM}Live home:    ${NC} $LIVE_HOME"
echo ""

# ─── Plugin Comparison ───
echo -e "${BOLD}Active Plugins${NC}"

MISSING_LOCAL=""
EXTRA_LOCAL=""
VERSION_DIFF=""
MATCHING=0

while IFS= read -r line; do
    [ -z "$line" ] && continue
    plugin_name=$(echo "$line" | cut -d',' -f1)
    [ -z "$plugin_name" ] && continue
    if ! echo "$LOCAL_PLUGINS" | grep -q "^${plugin_name},"; then
        MISSING_LOCAL="${MISSING_LOCAL}\n    ${RED}✗${NC} ${plugin_name} (active on live, missing locally)"
        fail_count=$((fail_count + 1))
    fi
done <<< "$LIVE_PLUGINS"

while IFS= read -r line; do
    [ -z "$line" ] && continue
    plugin_name=$(echo "$line" | cut -d',' -f1)
    [ -z "$plugin_name" ] && continue
    if ! echo "$LIVE_PLUGINS" | grep -q "^${plugin_name},"; then
        EXTRA_LOCAL="${EXTRA_LOCAL}\n    ${YELLOW}~${NC} ${plugin_name} (active locally, not on live)"
        warn_count=$((warn_count + 1))
    fi
done <<< "$LOCAL_PLUGINS"

while IFS= read -r line; do
    [ -z "$line" ] && continue
    plugin_name=$(echo "$line" | cut -d',' -f1)
    live_ver=$(echo "$line" | cut -d',' -f2)
    [ -z "$plugin_name" ] && continue
    local_line=$(echo "$LOCAL_PLUGINS" | grep "^${plugin_name}," || echo "")
    if [ -n "$local_line" ]; then
        local_ver=$(echo "$local_line" | cut -d',' -f2)
        if [ "$local_ver" = "$live_ver" ]; then
            MATCHING=$((MATCHING + 1))
        else
            VERSION_DIFF="${VERSION_DIFF}\n    ${YELLOW}~${NC} ${plugin_name}: local=${local_ver} live=${live_ver}"
            warn_count=$((warn_count + 1))
        fi
    fi
done <<< "$LIVE_PLUGINS"

echo -e "  ${GREEN}✓${NC} ${MATCHING} plugins match exactly (name + version)"
echo -e "  ${DIM}  Local: ${LOCAL_PLUGIN_COUNT} active | Live: ${LIVE_PLUGIN_COUNT} active${NC}"

if [ -n "$MISSING_LOCAL" ]; then
    echo -e "\n  ${RED}Missing locally:${NC}"
    echo -e "$MISSING_LOCAL"
fi

if [ -n "$VERSION_DIFF" ]; then
    echo -e "\n  ${YELLOW}Version differences:${NC}"
    echo -e "$VERSION_DIFF"
fi

if [ -n "$EXTRA_LOCAL" ]; then
    echo -e "\n  ${YELLOW}Extra local plugins:${NC}"
    echo -e "$EXTRA_LOCAL"
fi

echo ""

# ─── Summary ───
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
total=$((pass + warn_count + fail_count))
if [ $fail_count -eq 0 ] && [ $warn_count -eq 0 ]; then
    echo -e "  ${GREEN}✓ All ${total} checks passed — environments match!${NC}"
elif [ $fail_count -eq 0 ]; then
    echo -e "  ${YELLOW}~ ${pass} passed, ${warn_count} warnings, ${fail_count} failures${NC}"
    echo -e "  ${DIM}  Warnings are usually minor version differences.${NC}"
else
    echo -e "  ${RED}✗ ${pass} passed, ${warn_count} warnings, ${fail_count} failures${NC}"
    echo -e "  ${DIM}  Failures indicate missing plugins or config mismatches.${NC}"
    echo -e "  ${DIM}  Run ./sync-from-live.sh to re-sync.${NC}"
fi
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
